### PR TITLE
Fix readme and scripts

### PR DESCRIPTION
**Pull request by alexkogon**

### CODE REVIEW

**Comment by alexkogon** [comment]
Will do a single merge when current issues that weren't before encountered are resolved

**Comment by jguglielmi** [comment]
Sounds good!  I'm eager to check it out!  I just used the eclipse m2e util because it was integrated nicely into Eclipse.

**Comment by alexkogon** [comment]
Hi Jaison!

Nice to hear back from you, sorry I have been a bit hectic with various things and haven't had a chance to respond yet.

I was actually wrong; the changes we did to the code to not require Eclipse any more worked fine, it was the single executable JAR that was causing problems (I had misunderstood my coworkers) so we can go ahead and merge this stuff at some point soon.

We also are working on a new validation set to make sure all the functionality works on Windows as a baseline, which we would be happy to merge into your master; I spent quite a bit of time the other day figuring out that the demos I pulled from you weren't working :)

Finally we are trying to get this all built up into a single executable JAR that we can move around to run OASIS without needing any other files (except the actual Wiki content of course). I added the main class attribute to your pom.xml file to create an executable JAR, and we are able to run OASIS but when we try to run a test the generated Java command has the wrong classpath. The fix for this is within the Fitnesse code itself, so I have already started diving in there to get that fixed...

Once we have a stable version that we can run from just the JAR we will be happy but until then I am ready to contribute a good amount of time to getting the project there, so I will work in our dockpack group and send you pull requests.

Also I got approval from Cloudbees to get a free Jenkins instance in the cloud for us to run Continuous Integration on the OASIS project, we should probably build some more automated tests to run to make sure it is working.

I'll be working on this stuff this week, feel free to get in touch whenever, maybe we can start a conversation on getting the work we did up into your top level project.

Hope you are well!

Alex

**Comment by jguglielmi** [comment]
Alex,

We will indeed be in touch! I'm glad you found the project and enjoy it!

Thanks,

Jaison Guglielmi

**Pull request closed without merging**
